### ISSUE TITLE
选择器 Picker组件层叠式选择器问题

### ISSUE THREAD

**Issue by yuweilan** [ZhonganTechENG/zarm-vue#12]
![1520913465059](https://user-images.githubusercontent.com/11817795/37321948-c981b4bc-26b5-11e8-8daf-21874c59638f.jpg)

![1520913421409](https://user-images.githubusercontent.com/11817795/37321921-a9b12b90-26b5-11e8-8b7c-d8a39658a30b.jpg)
￼请问如上所示多层级连时，如何只选中部分级连，并捕捉到变化（部分级连点击蒙层，会有值在input里，但是无法watch到变化

**Comment by chuanshuoye** [comment]
你现在用的是哪个版本，1.0.7是么？

**Comment by chuanshuoye** [comment]
针对1.0.x版本的可以升级到1.0.8版本，修正了这个问题，可以通过v-model自动监听到watch，或者使用@change绑定值变化事件；
